[package]
name = "tracelogging-wpp-bench"
version = "0.1.0"
edition = "2021"

[dependencies]
tracelogging = "1"
wpp = { git = "https://github.com/gurry/windows-drivers-rs.git", branch = "wdf-wpp" }

[[bench]]
name = "compare"
harness = false

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
